### ISSUE TITLE
SQL error 1213 for Multi Proxies

### ISSUE THREAD

**Issue by PanHaskins** [BlackDemonZyT/BotSentry#109]
Proxies version:
Flamecord 1.5.9
BotSentry 9.5.3

Each Bungeecord has this bug at different times. None is the same.
No one even has to be on the server for it to do it.

Proxy Log 1:
[20:55:17 INFO]: (!) SQL error is 1213.
[20:56:17 INFO]: (!) SQL error is 1213.
[13:29:17 INFO]: (!) SQL error is 1213.
[13:30:17 INFO]: (!) SQL error is 1213.

Proxy Log 2:
[00:32:52 INFO]: (!) SQL error is 1213.
[00:33:53 INFO]: (!) SQL error is 1213.
[00:35:53 INFO]: (!) SQL error is 1213.
[03:03:28 INFO]: (!) SQL error is 1213.
[03:06:29 INFO]: (!) SQL error is 1213.

**Comment by Laurenshup** [comment]
This message is not displayed at the same time? What is your database setup?

**Comment by PanHaskins** [comment]
```
whitelist-database-sync:
  enabled: true
  cachetime: 120
  
mysql:
  settings:
    updateinterval: 60
  port: 3306
  username: "asfasafasf"
  database: "s1_databasename"
  password: "bestpasswordever"
  ip: "141.141.141.141"
  enabled: true
```
