### ISSUE TITLE
Possibility to change the /bs command in the config

### ISSUE THREAD

**Issue by Soulaen** [BlackDemonZyT/BotSentry#127]
The plugin does not let you change the command by creating an old config, the thing is that it interferes with the work of the plugin BossShopPro I would like to just change the command but I can not do it.

```yml
# Command specific settings
commands:
  bs:
    # Should the /bs blacklist clear and /bs whitelist clear ask to confirm the request with a code?
    # Recommended if you give the permission to clear the blacklist/whitelist to a non-experienced user
    clearconfirmation: true
    accounts:
      # The amount of different IPs per page.
      defaultpagesize: 6
    notifications:
      # The refresh rate in milliseconds on which the notifications provider checks
      # for players with the botsentry.automaticnotification permission.
      permissionchecktime: 10000
      # The minimum number of bad packets in a second, to display the notifications bar.
      minimumbadpackets: 4
  bsw:
    search:
      # Amount of results per page in the Wiki search menu
      resultpagesize: 6
      # The size of the context before and after the searched word.
      # 1 meaning only one word before and after the searched word etc.
      resultcontext: 2
```

**Comment by Laurenshup** [comment]
I am not fully understanding what you are requesting here.

**Comment by Soulaen** [comment]
I want to change the command in the configuration as follows or disable the shorthand altogether I need to have no /bs command in the plugin
```yml
# Command specific settings
commands:
  bss:
    # Should the /bs blacklist clear and /bs whitelist clear ask to confirm the request with a code?
    # Recommended if you give the permission to clear the blacklist/whitelist to a non-experienced user
    clearconfirmation: true
    accounts:
      # The amount of different IPs per page.
      defaultpagesize: 6
    notifications:
      # The refresh rate in milliseconds on which the notifications provider checks
      # for players with the botsentry.automaticnotification permission.
      permissionchecktime: 10000
      # The minimum number of bad packets in a second, to display the notifications bar.
      minimumbadpackets: 4
  bsw:
    search:
      # Amount of results per page in the Wiki search menu
      resultpagesize: 6
      # The size of the context before and after the searched word.
      # 1 meaning only one word before and after the searched word etc.
      resultcontext: 2
```
Because the /bs command conflicts with another plugin that has the same command.
The problem is that when you try to save and reload the plugin, the settings are not applied and an old config is created.
